packages:
  - "packages/*"

catalog:
  # 打包
  rollup: ^4.24.0
  "@rollup/plugin-typescript": ^12.1.1 # 打包时， 运行typescript检测， 和生成d.ts
  tslib: ^2.8.0 # 附属的库
  "@rollup/plugin-terser": ^0.4.4 # 打包时， 压缩代码

  # 打包时， 从ts文件， 生成d.ts
  typescript: ^5.6.3

  # 开发时 - 代码风格检测
  prettier: ^3.3.3

  # 开发时 - 语法检测
  eslint: ^9.13.0
  "@eslint/js": ^10.0.0 # eslint官方推荐的配置项（检测js文件）
  "@types/eslint__js": ^8.42.3 # 上一个的类型文件， 不安装就报错

  # 开发时 - 测试
  jest: ^29.7.0
  "@jest/globals": ^29.7.0 # 编写测试用例时， 导入test等测试函数
  babel-jest: ^29.7.0 # 让jest可以运行ts扩展名的测试用例
  "@babel/core": ^7.25.9 # babel-jest基于babel
  "@babel/preset-env": ^7.25.9
  "@babel/preset-typescript": ^7.25.9 # 让babel可以编译ts

  # 提交前 - 提交规范检测
  "@commitlint/cli": ^19.5.0
  "@commitlint/config-conventional": ^19.5.0

  # 提交前, 做检测
  husky: ^9.1.6 # 提交时，触发钩子，来做做上述检测
  lint-staged: ^15.2.10 # 让husky只检测暂存内容

  # 发布
  "@changesets/cli": ^2.27.9 # 子项目的版本管理
